-- 전년 비교 및 고성장 뱃지용 칼럼 추가
ALTER TABLE style_data ADD COLUMN IF NOT EXISTS prev_comparison JSONB DEFAULT '{}';
ALTER TABLE style_data ADD COLUMN IF NOT EXISTS high_growth BOOLEAN DEFAULT FALSE;
ALTER TABLE style_data ADD COLUMN IF NOT EXISTS growth_ratio REAL DEFAULT 0;

ALTER TABLE color_data ADD COLUMN IF NOT EXISTS prev_comparison JSONB DEFAULT '{}';
ALTER TABLE color_data ADD COLUMN IF NOT EXISTS high_growth BOOLEAN DEFAULT FALSE;
ALTER TABLE color_data ADD COLUMN IF NOT EXISTS growth_ratio REAL DEFAULT 0;
